project_id: 'genai-project-429612'
location: 'us-central1'
dataset_id: 'hackathon_data'
table_id: 'cars_co2_emission'
pdf_file_uri: 'gs://cloud-videos/gcp x formula e hackathon data/FormulaE2023Report-FINAL-.pdf'
llm_model_name: 'gemini-1.5-flash-001'
background_image_location: './MASTER-STILL-Gen3_FrontAerial_Combo.jpg'